# Site settings
title: Mike Lippincott
email: 1michaell2017@gmail.com
url: https://mikelippincott.github.io
description: ""
keywords: ""
skills: "Computational Cell Biologist - PhD Candidate"
university: "University of Colorado Anschutz Medical Campus"
meta_author: Lippincott Michael

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1BBFA1
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2C3759 #FD6E8A
  secondary-dark: 1BA698 #A2122F

# Footer settings
footer:
  copyright: Michael J. Lippincott
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/MikeLippincott
  - title: x
    url: https://x.com/mike_lippincott
  - title: linkedin
    url: https://www.linkedin.com/in/mlippincott/
  - title: orcid
    url: https://orcid.org/0000-0002-8637-1448


# Postal address (add as many lines as necessary)
address:
  - line: Denver, CO

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
